FRUIT_PERIOD_LENGTH = 8

nSubsidyHalvingInterval = 16
COIN = 100000000

FEE_FRACTION_C1_NUMERATOR = 1
FEE_FRACTION_C1_DENOMINATOR = 100

REWARD_DIFF_FRACTION_C3_NUMERATOR = 1
REWARD_DIFF_FRACTION_C3_DENOMINATOR = 100

REWARD_CREATE_FRACTION_C2_NUMERATOR = 1
REWARD_CREATE_FRACTION_C2_DENOMINATOR = 10
